import Head from 'next/head'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useQuery } from "@tanstack/react-query";
// const inter = Inter({ subsets: ['latin'] })
import { usePokemonIndex } from "@/utils/fetch-hooks";
import PokeCard from "@/components/pokecard";

export default function Home() {
  const { data } = usePokemonIndex();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
          gridTemplateRows: "repeat(5, 1fr)",
        }}
      >
        {data?.results.map((item) => (
          <PokeCard key={item.name} name={item.name} url={item.url}></PokeCard>
        ))}
      </main>
    </>
  );
}
