import Head from 'next/head'
import Link from "next/link";
import { usePokemonQuery } from "@/utils/fetch-hooks";
import PokeCard from "@/components/pokecard";
import Layout from "@/components/layout";

type Pokemon = {
  id: number;
  name: Record<string, string>;
  type: string[];
  base: Record<string, number>;
  image: string;
};

type HomeProps = { data: Pokemon[] };

export default function Home() {
  const { data } = usePokemonQuery();
  return (
    <>
      <Head>
        <title>Another Pokemon Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="grid grid-cols-auto-fit grid-rows-4 mx-auto gap-x-6 gap-y-6 place-items-center p-4">
          {data?.map((item) => (
            <Link key={item.name.english} href={`/detail/${item.name.english}`}>
              <PokeCard
                image={item.image}
                name={item.name.english}
                type={item.type}
                id={item.id}
              />
            </Link>
          ))}
        </section>
      </Layout>
    </>
  );
}

// export async function getServerSideProps() {
//   let data = await fetch("http://localhost:3000/api/pokemon");
//   data = await data.json();
//   return {
//     props: {
//       data,
//     },
//   };
// }